language: python

dist: xenial

cache: false

sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - pip install -r requirements.txt

install:
  - python setup.py build_ext --inplace --force --define CYTHON_TRACE

script:
  - coverage run -m py.test tests
  - coverage report

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change

