name: Upload Python Package

on:
  release:
    types: [created]

jobs:     
  deploy:
    strategy:
        matrix:
          runs-on: [windows-latest]
          python-version: [3.5, 3.6, 3.7, 3.8]
    runs-on:  ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
